# Generated by Django 3.2.20 on 2023-09-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datbase',
            name='profession',
            field=models.CharField(default='', max_length=200),
        ),
    ]
