# Generated by Django 3.2.20 on 2023-09-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_datbase_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='datbase',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
